appId: 'com.darkswap.trading'
productName: 'Darkswap Trading Tool'
artifactName: '${productName}-setup-${version}-prod.${ext}'
directories:
  output: 'release/prod'
asarUnpack:
  - '**/node_modules/better-sqlite3/**'
files:
  - 'dist/**/**/*'
  - 'package.json'
extraResources:
  - from: 'config/prod/config.yaml'
    to: 'config.yaml'
  - from: 'assets/icon.ico'
    to: 'icon.ico'
win:
  target:
    - target: 'nsis'
      arch:
        - 'x64'
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: 'assets/icon.icns'
linux:
  target:
    - 'AppImage'
